name: 🚀 Deploy to cPanel on push!

on: 
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      # actions/checkout@v3 is a prebuilt GitHub action to fetch the latest code from the repository
      uses: actions/checkout@v3 

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies 📦
      run: npm install
      
    - name: 🔨 Build React Project
      run: npm run build
    
    - name: 📂 Upload to cPanel via SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.CPANEL_FTP_SERVER }}
        username: ${{ secrets.CPANEL_FTP_USERNAME }}
        password: ${{ secrets.CPANEL_FTP_ACCOUNT_PWD }}
        local-dir: ./dist/        # The built Vite files
        server-dir: public_html # The target directory on Namecheap
        port: 21098